version = 1

[[annotations]]
path = [
    ".gitignore",
    "REUSE.toml",
    "bin/*",
    "contrib/api.endowment.dev.service",
    "go.mod",
    "go.sum",
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"
